### ISSUE TITLE
21.5 寸成功案例 + 1

### ISSUE THREAD

**Issue by hank9999** [HelloworldDk/dkmaiproj#1]
感谢您的教程 和 先行者的努力，让DIY手台不再困难！

21.5寸 16:9 屏幕 将所有的漆包线搓在一起捋到同一侧, 再接mpr121也能够正常运行
mpr121模块可能有漏电的, 到货后可以先上电试试, 漏电的会发热
2mm 亚克力板强度不够 下面垫了一个有点状网格的4mm亚力克板

物料清单:
 - 使用 SAMD21 MINI 开发板 (31.5元)
 - 2张 40欧的 ito 膜 (剩余半张) (70元)
 - MPR121 模块 4个 (14.88元)
 - 2mm 亚克力板 (10元)
 - 3.5卷 0.1mm漆包线
 - 面包板 + 杜邦线若干

![QQ图片20230613233430](https://github.com/HelloworldDk/dkmaiproj/assets/20784591/ece021ce-62ef-46ca-8ab8-a29100022cba)
![QQ图片20230613234821](https://github.com/HelloworldDk/dkmaiproj/assets/20784591/dbbfec5c-0522-4626-ada6-adeb199f3223)

**Comment by romanticfire** [comment]
这是一个多么幸福的玩家啊
感谢开源方案喵

**Comment by HelloworldDk** [comment]
做得很好，但是I2C线还是建议焊接的说））

**Comment by hank9999** [comment]
> 做得很好，但是I2C线还是建议焊接的说））

已经发现问题了，前几天打着打着杜邦线掉了😂
